[package]
name = "formdial"
version = "0.2.0"
authors = ["gemmarx"]
edition = "2018"


[dependencies]
web-view = { version = "0.6.3", features = ["edge"] }
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
base64 = "0.13.0"
serde = "1.0.116"
serde_json = "1.0.58"
convert_case = "0.4.0"

